import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Theme = "light" | "dark";
export type FontSize = "small" | "medium" | "large";
export type Language = "en" | "ms" | "zh" | "ta";

interface SettingsState {
  theme: Theme;
  fontSize: FontSize;
  language: Language;
  setTheme: (t: Theme) => void;
  setFontSize: (s: FontSize) => void;
  setLanguage: (l: Language) => void;
  t: (key: string) => string;
}

const SettingsContext = createContext<SettingsState | null>(null); // context

const fontSizeClass: Record<FontSize, string> = {
  small: "text-sm",
  medium: "text-base",
  large: "text-lg",
};

const fontSizeRoot: Record<FontSize, string> = {
  small: "14px",
  medium: "16px",
  large: "18px",
};

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>(() => (localStorage.getItem("agro-theme") as Theme) || "light");
  const [fontSize, setFontSizeState] = useState<FontSize>(() => (localStorage.getItem("agro-fontsize") as FontSize) || "medium");
  const [language, setLanguageState] = useState<Language>(() => (localStorage.getItem("agro-lang") as Language) || "en");

  const setTheme = (t: Theme) => { setThemeState(t); localStorage.setItem("agro-theme", t); };
  const setFontSize = (s: FontSize) => { setFontSizeState(s); localStorage.setItem("agro-fontsize", s); };
  const setLanguage = (l: Language) => { setLanguageState(l); localStorage.setItem("agro-lang", l); };

  useEffect(() => {
    document.documentElement.classList.toggle("dark", theme === "dark");
  }, [theme]);

  useEffect(() => {
    document.documentElement.style.fontSize = fontSizeRoot[fontSize];
  }, [fontSize]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <SettingsContext.Provider value={{ theme, fontSize, language, setTheme, setFontSize, setLanguage, t }}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const ctx = useContext(SettingsContext);
  if (!ctx) throw new Error("useSettings must be inside SettingsProvider");
  return ctx;
}

// Translation dictionary
const translations: Record<string, Record<string, string>> = {
  en: {
    // Sidebar
    "nav.advisory": "Advisory",
    "nav.overview": "Overview",
    "nav.weather": "Weather Forecast",
    "nav.market": "Market Prices",
    "nav.crops": "Crop Advisory",
    "nav.seedIntegrity": "Seed Integrity",
    "nav.scanner": "Seed Scanner",
    "nav.evidence": "Evidence Locker",
    "nav.planner": "Catch-Up Planner",
    "nav.system": "System",
    "nav.alerts": "Alerts",
    "nav.settings": "Settings",
    "nav.collapse": "Collapse",
    // Header
    "header.search": "Search anything...",
    "header.allSystems": "All Systems Operational",
    // Overview
    "overview.status": "System Status:",
    "overview.operational": "Operational",
    "overview.risks": "2 Risks Detected in Kedah District",
    "overview.activeCrops": "Active Crops",
    "overview.pendingScans": "Pending Scans",
    "overview.alerts": "Alerts",
    "overview.reports": "Reports",
    "overview.recentActivity": "Recent Activity",
    "overview.floodWarning": "Flood warning issued for Kedah & Perlis",
    "overview.padiScan": "Padi MR220 scan: Anomaly detected — Padi Angin in 38% of samples",
    "overview.mungBean": "Mung Bean scan: Healthy seedlings confirmed, 94% germination",
    "overview.gingerPrice": "Ginger market price surged +12.1% — optimal planting window",
    // Weather
    "weather.title": "Weather Forecast",
    "weather.subtitle": "Kedah District — MET Malaysia Data",
    "weather.floodActive": "Flood Warning Active",
    "weather.floodDesc": "Heavy rainfall expected in Kedah & Perlis for next 48 hours. Delay outdoor operations.",
    "weather.temperature": "Temperature",
    "weather.rainfall": "Rainfall",
    "weather.wind": "Wind",
    "weather.humidity": "Humidity",
    "weather.feelsLike": "Feels like 31°C",
    "weather.heavy": "Heavy — 42mm expected",
    "weather.neDirection": "NE Direction",
    "weather.veryHigh": "Very High",
    "weather.highLow": "High / Low",
    "weather.rain": "Rain",
    "weather.source": "Source: MET Malaysia API • Updated every 6 hours",
    // Weather days
    "weather.today": "Today",
    "weather.heavyRain": "Heavy Rain",
    "weather.cloudy": "Cloudy",
    "weather.clear": "Clear",
    "weather.rain2": "Rain",
    "weather.partlyCloudy": "Partly Cloudy",
    // Market
    "market.title": "Market Prices",
    "market.subtitle": "FAMA Live Data — Malaysian Agricultural Commodities",
    "market.topGainer": "Top Gainer",
    "market.topLoser": "Top Loser",
    "market.mostTraded": "Most Traded",
    "market.crop": "Crop",
    "market.price": "Price",
    "market.change": "Change",
    "market.weekHigh": "Week High",
    "market.weekLow": "Week Low",
    "market.volume": "Volume",
    // Crops
    "crops.title": "Crop Advisory",
    "crops.subtitle": "AI-powered recommendations based on climate, market, and regional data",
    // Scanner
    "scanner.title": "Seed Scanner",
    "scanner.subtitle": "Upload seedling photos for AI-powered integrity analysis",
    "scanner.upload": "Upload Seedling Photo",
    "scanner.dragDrop": "Drag & drop or click to browse • 7–14 day old seedlings",
    "scanner.gpsNote": "GPS location and timestamp will be recorded automatically",
    "scanner.history": "Scan History",
    "scanner.healthy": "Healthy",
    "scanner.anomaly": "Anomaly Detected",
    "scanner.germination": "Germination Rate:",
    "scanner.generateReport": "Generate Evidence Report",
    // Evidence
    "evidence.title": "Evidence Locker",
    "evidence.subtitle": "Signed reports with GPS, weather, and AI analysis for legal claims",
    "evidence.download": "Download Report (PDF)",
    "evidence.anomalySigned": "Anomaly — Signed PDF",
    "evidence.verifiedClean": "Verified — Clean",
    // Planner
    "planner.title": "Catch-Up Planner",
    "planner.subtitle": "Rescue crop recommendations based on remaining season window",
    "planner.seasonRemaining": "Season Remaining",
    "planner.failedBatches": "Failed Batches",
    "planner.recoveryOptions": "Recovery Options",
    "planner.harvestTime": "Harvest Time",
    "planner.waterNeeds": "Water Needs",
    "planner.marketPrice": "Market Price",
    "planner.suitability": "Suitability",
    "planner.available": "Available",
    "planner.limited": "Limited",
    // Alerts
    "alerts.title": "Alerts & Notifications",
    "alerts.markAllRead": "Mark all read",
    "alerts.unread": "3 unread alerts requiring attention",
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account preferences and farm configuration",
    "settings.profile": "Profile",
    "settings.farm": "Farm Settings",
    "settings.notifications": "Notifications",
    "settings.display": "Display",
    "settings.regional": "Regional",
    "settings.privacy": "Privacy & Security",
    "settings.fullName": "Full Name",
    "settings.email": "Email Address",
    "settings.phone": "Phone Number",
    "settings.role": "Role",
    "settings.farmName": "Farm Name",
    "settings.district": "District",
    "settings.state": "State",
    "settings.acreage": "Total Acreage (hectares)",
    "settings.primaryCrop": "Primary Crop",
    "settings.secondaryCrops": "Secondary Crops",
    "settings.soilType": "Soil Type",
    "settings.save": "Save Changes",
    "settings.alertTypes": "Alert Types",
    "settings.weatherAlerts": "Weather Alerts",
    "settings.weatherAlertsDesc": "Flood, drought, and storm warnings",
    "settings.marketUpdates": "Market Price Updates",
    "settings.marketUpdatesDesc": "Price changes for tracked crops",
    "settings.cropAdvisory": "Crop Advisory",
    "settings.cropAdvisoryDesc": "Planting and harvesting recommendations",
    "settings.seedScanResults": "Seed Scan Results",
    "settings.seedScanResultsDesc": "Scan completion and anomaly alerts",
    "settings.delivery": "Delivery",
    "settings.emailDigest": "Email Digest",
    "settings.emailDigestDesc": "Daily summary via email",
    "settings.smsAlerts": "SMS Alerts",
    "settings.smsAlertsDesc": "Critical alerts via SMS",
    "settings.soundEffects": "Sound Effects",
    "settings.soundEffectsDesc": "Play sounds for in-app notifications",
    "settings.quietHours": "Quiet Hours",
    "settings.start": "Start",
    "settings.end": "End",
    "settings.theme": "Theme",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.fontSizeLabel": "Font Size",
    "settings.small": "Small",
    "settings.medium": "Medium",
    "settings.large": "Large",
    "settings.compactMode": "Compact Mode",
    "settings.compactModeDesc": "Reduce spacing for denser layout",
    "settings.animations": "Animations",
    "settings.animationsDesc": "Enable motion and transitions",
    "settings.language": "Language",
    "settings.tempUnit": "Temperature Unit",
    "settings.dateFormat": "Date Format",
    "settings.timezone": "Timezone",
    "settings.currency": "Currency",
    "settings.shareLocation": "Share Location Data",
    "settings.shareLocationDesc": "Allow weather and advisory features to use your farm location",
    "settings.analyticsOptIn": "Analytics Opt-in",
    "settings.analyticsOptInDesc": "Help improve the platform by sharing anonymous usage data",
    "settings.publicProfile": "Public Profile",
    "settings.publicProfileDesc": "Allow other farmers in your district to see your profile",
    "settings.twoFactor": "Two-Factor Authentication",
    "settings.twoFactorDesc": "Add an extra layer of security to your account",
    "settings.dataExport": "Data Export",
    "settings.dataExportDesc": "Allow downloading your farm data and reports",
    "settings.accountActions": "Account Actions",
    "settings.exportData": "Export My Data",
    "settings.deleteAccount": "Delete Account",
    "settings.saved": "Settings saved",
    "settings.savedDesc": "Your preferences have been updated successfully.",
    // Simulator
    "nav.simulator": "Risk Simulator",
    "simulator.title": "Farm Risk Simulator",
    "simulator.subtitle": "Simulate the impact of weather, market, and seed quality on your crop plan",
    "simulator.selectCrops": "Select Your Crop Plan",
    "simulator.scenarios": "Scenario Parameters",
    "simulator.weatherChange": "Weather Scenario",
    "simulator.weatherNormal": "Normal Season",
    "simulator.weatherMoreRain": "More Rainfall",
    "simulator.weatherDrought": "Drought",
    "simulator.weatherMonsoon": "Monsoon Shift",
    "simulator.weatherFlood": "Flood Risk",
    "simulator.weatherHeatwave": "Heatwave",
    "simulator.weatherLaNina": "La Niña",
    "simulator.weatherElNino": "El Niño",
    "simulator.cropPreset": "Select Crop",
    "simulator.cropCustom": "Type Manually",
    "simulator.cropPhoto": "Photo Identify",
    "simulator.cropPhotoDesc": "Take or upload a photo — AI will identify the crop for you.",
    "simulator.addCustomCrop": "Add",
    "simulator.identifyingCrop": "AI is identifying your crop...",
    "simulator.marketFluctuation": "Market Fluctuation",
    "simulator.seedQuality": "Seed Quality",
    "simulator.germination": "germination",
    "simulator.runSimulation": "Run Simulation",
    "simulator.reset": "Reset",
    "simulator.totalRevenue": "Total Expected Revenue",
    "simulator.estimatedSeason": "Estimated for this season",
    "simulator.avgFailureRisk": "Avg. Failure Risk",
    "simulator.lowRisk": "Low risk — favorable conditions",
    "simulator.moderateRisk": "Moderate risk — proceed with caution",
    "simulator.highRisk": "High risk — consider alternatives",
    "simulator.cropsPlanned": "Crops Planned",
    "simulator.diversification": "Crop diversification",
    "simulator.cropBreakdown": "Crop-by-Crop Breakdown",
    "simulator.simulatedOutcome": "Simulated outcome",
    "simulator.profitable": "Profitable",
    "simulator.moderateRiskLabel": "Moderate Risk",
    "simulator.highRiskLabel": "High Risk",
    "simulator.estYield": "Est. Yield",
    "simulator.estRevenue": "Est. Revenue",
    "simulator.failureRisk": "Failure Risk",
    // Footer
    "footer.farmer": "Farmer",
    // Misc
    "days": "days",
    "active": "Active",
  },
  ms: {
    "nav.advisory": "Nasihat",
    "nav.overview": "Gambaran Keseluruhan",
    "nav.weather": "Ramalan Cuaca",
    "nav.market": "Harga Pasaran",
    "nav.crops": "Nasihat Tanaman",
    "nav.seedIntegrity": "Integriti Benih",
    "nav.scanner": "Pengimbas Benih",
    "nav.evidence": "Loker Bukti",
    "nav.planner": "Perancang Pemulihan",
    "nav.system": "Sistem",
    "nav.alerts": "Makluman",
    "nav.settings": "Tetapan",
    "nav.collapse": "Kecilkan",
    "header.search": "Cari apa sahaja...",
    "header.allSystems": "Semua Sistem Beroperasi",
    "overview.status": "Status Sistem:",
    "overview.operational": "Beroperasi",
    "overview.risks": "2 Risiko Dikesan di Daerah Kedah",
    "overview.activeCrops": "Tanaman Aktif",
    "overview.pendingScans": "Imbasan Tertangguh",
    "overview.alerts": "Makluman",
    "overview.reports": "Laporan",
    "overview.recentActivity": "Aktiviti Terkini",
    "overview.floodWarning": "Amaran banjir dikeluarkan untuk Kedah & Perlis",
    "overview.padiScan": "Imbasan Padi MR220: Anomali dikesan — Padi Angin dalam 38% sampel",
    "overview.mungBean": "Imbasan Kacang Hijau: Anak benih sihat disahkan, 94% percambahan",
    "overview.gingerPrice": "Harga pasaran halia melonjak +12.1% — masa penanaman optimum",
    "weather.title": "Ramalan Cuaca",
    "weather.subtitle": "Daerah Kedah — Data MET Malaysia",
    "weather.floodActive": "Amaran Banjir Aktif",
    "weather.floodDesc": "Hujan lebat dijangka di Kedah & Perlis untuk 48 jam seterusnya. Tangguhkan operasi luar.",
    "weather.temperature": "Suhu",
    "weather.rainfall": "Hujan",
    "weather.wind": "Angin",
    "weather.humidity": "Kelembapan",
    "weather.feelsLike": "Terasa seperti 31°C",
    "weather.heavy": "Lebat — 42mm dijangka",
    "weather.neDirection": "Arah Timur Laut",
    "weather.veryHigh": "Sangat Tinggi",
    "weather.highLow": "Tinggi / Rendah",
    "weather.rain": "Hujan",
    "weather.source": "Sumber: API MET Malaysia • Dikemas kini setiap 6 jam",
    "weather.today": "Hari Ini",
    "weather.heavyRain": "Hujan Lebat",
    "weather.cloudy": "Mendung",
    "weather.clear": "Cerah",
    "weather.rain2": "Hujan",
    "weather.partlyCloudy": "Separuh Mendung",
    "market.title": "Harga Pasaran",
    "market.subtitle": "Data FAMA — Komoditi Pertanian Malaysia",
    "market.topGainer": "Kenaikan Tertinggi",
    "market.topLoser": "Penurunan Tertinggi",
    "market.mostTraded": "Paling Didagangkan",
    "market.crop": "Tanaman",
    "market.price": "Harga",
    "market.change": "Perubahan",
    "market.weekHigh": "Tinggi Minggu",
    "market.weekLow": "Rendah Minggu",
    "market.volume": "Jumlah",
    "crops.title": "Nasihat Tanaman",
    "crops.subtitle": "Cadangan berkuasa AI berdasarkan data iklim, pasaran, dan kawasan",
    "scanner.title": "Pengimbas Benih",
    "scanner.subtitle": "Muat naik foto anak benih untuk analisis integriti AI",
    "scanner.upload": "Muat Naik Foto Anak Benih",
    "scanner.dragDrop": "Seret & lepas atau klik untuk memilih • Anak benih 7–14 hari",
    "scanner.gpsNote": "Lokasi GPS dan cap waktu akan direkod secara automatik",
    "scanner.history": "Sejarah Imbasan",
    "scanner.healthy": "Sihat",
    "scanner.anomaly": "Anomali Dikesan",
    "scanner.germination": "Kadar Percambahan:",
    "scanner.generateReport": "Jana Laporan Bukti",
    "evidence.title": "Loker Bukti",
    "evidence.subtitle": "Laporan bertandatangan dengan GPS, cuaca, dan analisis AI untuk tuntutan undang-undang",
    "evidence.download": "Muat Turun Laporan (PDF)",
    "evidence.anomalySigned": "Anomali — PDF Bertandatangan",
    "evidence.verifiedClean": "Disahkan — Bersih",
    "planner.title": "Perancang Pemulihan",
    "planner.subtitle": "Cadangan tanaman pemulihan berdasarkan baki musim",
    "planner.seasonRemaining": "Baki Musim",
    "planner.failedBatches": "Kelompok Gagal",
    "planner.recoveryOptions": "Pilihan Pemulihan",
    "planner.harvestTime": "Masa Tuai",
    "planner.waterNeeds": "Keperluan Air",
    "planner.marketPrice": "Harga Pasaran",
    "planner.suitability": "Kesesuaian",
    "planner.available": "Tersedia",
    "planner.limited": "Terhad",
    "alerts.title": "Makluman & Pemberitahuan",
    "alerts.markAllRead": "Tandai semua dibaca",
    "alerts.unread": "3 makluman belum dibaca memerlukan perhatian",
    "settings.title": "Tetapan",
    "settings.subtitle": "Urus keutamaan akaun dan konfigurasi ladang anda",
    "settings.profile": "Profil",
    "settings.farm": "Tetapan Ladang",
    "settings.notifications": "Pemberitahuan",
    "settings.display": "Paparan",
    "settings.regional": "Serantau",
    "settings.privacy": "Privasi & Keselamatan",
    "settings.fullName": "Nama Penuh",
    "settings.email": "Alamat E-mel",
    "settings.phone": "Nombor Telefon",
    "settings.role": "Peranan",
    "settings.farmName": "Nama Ladang",
    "settings.district": "Daerah",
    "settings.state": "Negeri",
    "settings.acreage": "Jumlah Keluasan (hektar)",
    "settings.primaryCrop": "Tanaman Utama",
    "settings.secondaryCrops": "Tanaman Sekunder",
    "settings.soilType": "Jenis Tanah",
    "settings.save": "Simpan Perubahan",
    "settings.alertTypes": "Jenis Makluman",
    "settings.weatherAlerts": "Makluman Cuaca",
    "settings.weatherAlertsDesc": "Amaran banjir, kemarau, dan ribut",
    "settings.marketUpdates": "Kemas Kini Harga Pasaran",
    "settings.marketUpdatesDesc": "Perubahan harga tanaman yang dipantau",
    "settings.cropAdvisory": "Nasihat Tanaman",
    "settings.cropAdvisoryDesc": "Cadangan penanaman dan penuaian",
    "settings.seedScanResults": "Hasil Imbasan Benih",
    "settings.seedScanResultsDesc": "Pemberitahuan selesai imbasan dan anomali",
    "settings.delivery": "Penghantaran",
    "settings.emailDigest": "Ringkasan E-mel",
    "settings.emailDigestDesc": "Ringkasan harian melalui e-mel",
    "settings.smsAlerts": "Makluman SMS",
    "settings.smsAlertsDesc": "Makluman kritikal melalui SMS",
    "settings.soundEffects": "Kesan Bunyi",
    "settings.soundEffectsDesc": "Main bunyi untuk pemberitahuan dalam aplikasi",
    "settings.quietHours": "Waktu Senyap",
    "settings.start": "Mula",
    "settings.end": "Tamat",
    "settings.theme": "Tema",
    "settings.light": "Terang",
    "settings.dark": "Gelap",
    "settings.fontSizeLabel": "Saiz Fon",
    "settings.small": "Kecil",
    "settings.medium": "Sederhana",
    "settings.large": "Besar",
    "settings.compactMode": "Mod Padat",
    "settings.compactModeDesc": "Kurangkan jarak untuk susun atur lebih padat",
    "settings.animations": "Animasi",
    "settings.animationsDesc": "Dayakan gerakan dan peralihan",
    "settings.language": "Bahasa",
    "settings.tempUnit": "Unit Suhu",
    "settings.dateFormat": "Format Tarikh",
    "settings.timezone": "Zon Waktu",
    "settings.currency": "Mata Wang",
    "settings.shareLocation": "Kongsi Data Lokasi",
    "settings.shareLocationDesc": "Benarkan ciri cuaca dan nasihat menggunakan lokasi ladang anda",
    "settings.analyticsOptIn": "Ikut Serta Analitik",
    "settings.analyticsOptInDesc": "Bantu tingkatkan platform dengan berkongsi data penggunaan tanpa nama",
    "settings.publicProfile": "Profil Awam",
    "settings.publicProfileDesc": "Benarkan petani lain di daerah anda melihat profil anda",
    "settings.twoFactor": "Pengesahan Dua Faktor",
    "settings.twoFactorDesc": "Tambah lapisan keselamatan tambahan ke akaun anda",
    "settings.dataExport": "Eksport Data",
    "settings.dataExportDesc": "Benarkan muat turun data ladang dan laporan anda",
    "settings.accountActions": "Tindakan Akaun",
    "settings.exportData": "Eksport Data Saya",
    "settings.deleteAccount": "Padam Akaun",
    "settings.saved": "Tetapan disimpan",
    "settings.savedDesc": "Keutamaan anda telah dikemas kini dengan jayanya.",
    "nav.simulator": "Simulator Risiko",
    "simulator.title": "Simulator Risiko Ladang",
    "simulator.subtitle": "Simulasi kesan cuaca, pasaran, dan kualiti benih terhadap rancangan tanaman anda",
    "simulator.selectCrops": "Pilih Rancangan Tanaman",
    "simulator.scenarios": "Parameter Senario",
    "simulator.weatherChange": "Senario Cuaca",
    "simulator.weatherNormal": "Musim Biasa",
    "simulator.weatherMoreRain": "Lebih Hujan",
    "simulator.weatherDrought": "Kemarau",
    "simulator.weatherMonsoon": "Peralihan Monsun",
    "simulator.weatherFlood": "Risiko Banjir",
    "simulator.weatherHeatwave": "Gelombang Panas",
    "simulator.weatherLaNina": "La Niña",
    "simulator.weatherElNino": "El Niño",
    "simulator.cropPreset": "Pilih Tanaman",
    "simulator.cropCustom": "Taip Manual",
    "simulator.cropPhoto": "Foto Kenal Pasti",
    "simulator.cropPhotoDesc": "Ambil atau muat naik foto — AI akan mengenal pasti tanaman untuk anda.",
    "simulator.addCustomCrop": "Tambah",
    "simulator.identifyingCrop": "AI sedang mengenal pasti tanaman anda...",
    "simulator.marketFluctuation": "Turun Naik Pasaran",
    "simulator.seedQuality": "Kualiti Benih",
    "simulator.germination": "percambahan",
    "simulator.runSimulation": "Jalankan Simulasi",
    "simulator.reset": "Set Semula",
    "simulator.totalRevenue": "Jumlah Pendapatan Jangkaan",
    "simulator.estimatedSeason": "Anggaran untuk musim ini",
    "simulator.avgFailureRisk": "Purata Risiko Kegagalan",
    "simulator.lowRisk": "Risiko rendah — keadaan menggalakkan",
    "simulator.moderateRisk": "Risiko sederhana — teruskan dengan berhati-hati",
    "simulator.highRisk": "Risiko tinggi — pertimbangkan alternatif",
    "simulator.cropsPlanned": "Tanaman Dirancang",
    "simulator.diversification": "Kepelbagaian tanaman",
    "simulator.cropBreakdown": "Pecahan Setiap Tanaman",
    "simulator.simulatedOutcome": "Hasil simulasi",
    "simulator.profitable": "Menguntungkan",
    "simulator.moderateRiskLabel": "Risiko Sederhana",
    "simulator.highRiskLabel": "Risiko Tinggi",
    "simulator.estYield": "Anggaran Hasil",
    "simulator.estRevenue": "Anggaran Pendapatan",
    "simulator.failureRisk": "Risiko Kegagalan",
    "footer.farmer": "Petani",
    "days": "hari",
    "active": "Aktif",
  },
  zh: {
    "nav.advisory": "咨询",
    "nav.overview": "概览",
    "nav.weather": "天气预报",
    "nav.market": "市场价格",
    "nav.crops": "作物咨询",
    "nav.seedIntegrity": "种子完整性",
    "nav.scanner": "种子扫描仪",
    "nav.evidence": "证据柜",
    "nav.planner": "追赶规划",
    "nav.system": "系统",
    "nav.alerts": "警报",
    "nav.settings": "设置",
    "nav.collapse": "收起",
    "header.search": "搜索任何内容...",
    "header.allSystems": "所有系统正常运行",
    "overview.status": "系统状态：",
    "overview.operational": "运行中",
    "overview.risks": "吉打区检测到2个风险",
    "overview.activeCrops": "活跃作物",
    "overview.pendingScans": "待处理扫描",
    "overview.alerts": "警报",
    "overview.reports": "报告",
    "overview.recentActivity": "最近活动",
    "overview.floodWarning": "吉打和玻璃市发布洪水警告",
    "overview.padiScan": "稻谷MR220扫描：检测到异常 — 38%样本中含有野稻",
    "overview.mungBean": "绿豆扫描：确认健康幼苗，94%发芽率",
    "overview.gingerPrice": "生姜市场价格飙升+12.1% — 最佳种植窗口",
    "weather.title": "天气预报",
    "weather.subtitle": "吉打区 — 马来西亚气象局数据",
    "weather.floodActive": "洪水警告生效中",
    "weather.floodDesc": "吉打和玻璃市未来48小时预计有暴雨。暂停户外作业。",
    "weather.temperature": "温度",
    "weather.rainfall": "降雨",
    "weather.wind": "风力",
    "weather.humidity": "湿度",
    "weather.feelsLike": "体感31°C",
    "weather.heavy": "暴雨 — 预计42毫米",
    "weather.neDirection": "东北方向",
    "weather.veryHigh": "非常高",
    "weather.highLow": "最高 / 最低",
    "weather.rain": "降雨",
    "weather.source": "来源：马来西亚气象局API • 每6小时更新",
    "weather.today": "今天",
    "weather.heavyRain": "暴雨",
    "weather.cloudy": "多云",
    "weather.clear": "晴朗",
    "weather.rain2": "雨",
    "weather.partlyCloudy": "局部多云",
    "market.title": "市场价格",
    "market.subtitle": "FAMA实时数据 — 马来西亚农产品",
    "market.topGainer": "最大涨幅",
    "market.topLoser": "最大跌幅",
    "market.mostTraded": "交易最多",
    "market.crop": "作物",
    "market.price": "价格",
    "market.change": "变化",
    "market.weekHigh": "周最高",
    "market.weekLow": "周最低",
    "market.volume": "交易量",
    "crops.title": "作物咨询",
    "crops.subtitle": "基于气候、市场和区域数据的AI驱动建议",
    "scanner.title": "种子扫描仪",
    "scanner.subtitle": "上传幼苗照片进行AI完整性分析",
    "scanner.upload": "上传幼苗照片",
    "scanner.dragDrop": "拖放或点击浏览 • 7-14天幼苗",
    "scanner.gpsNote": "GPS位置和时间戳将自动记录",
    "scanner.history": "扫描历史",
    "scanner.healthy": "健康",
    "scanner.anomaly": "检测到异常",
    "scanner.germination": "发芽率：",
    "scanner.generateReport": "生成证据报告",
    "evidence.title": "证据柜",
    "evidence.subtitle": "包含GPS、天气和AI分析的签名报告，用于法律索赔",
    "evidence.download": "下载报告（PDF）",
    "evidence.anomalySigned": "异常 — 已签名PDF",
    "evidence.verifiedClean": "已验证 — 干净",
    "planner.title": "追赶规划",
    "planner.subtitle": "基于剩余季节窗口的补救作物建议",
    "planner.seasonRemaining": "剩余季节",
    "planner.failedBatches": "失败批次",
    "planner.recoveryOptions": "恢复选项",
    "planner.harvestTime": "收获时间",
    "planner.waterNeeds": "用水需求",
    "planner.marketPrice": "市场价格",
    "planner.suitability": "适合度",
    "planner.available": "可用",
    "planner.limited": "有限",
    "alerts.title": "警报与通知",
    "alerts.markAllRead": "全部标为已读",
    "alerts.unread": "3条未读警报需要关注",
    "settings.title": "设置",
    "settings.subtitle": "管理您的账户偏好和农场配置",
    "settings.profile": "个人资料",
    "settings.farm": "农场设置",
    "settings.notifications": "通知",
    "settings.display": "显示",
    "settings.regional": "区域",
    "settings.privacy": "隐私与安全",
    "settings.fullName": "全名",
    "settings.email": "电子邮件地址",
    "settings.phone": "电话号码",
    "settings.role": "角色",
    "settings.farmName": "农场名称",
    "settings.district": "地区",
    "settings.state": "州",
    "settings.acreage": "总面积（公顷）",
    "settings.primaryCrop": "主要作物",
    "settings.secondaryCrops": "次要作物",
    "settings.soilType": "土壤类型",
    "settings.save": "保存更改",
    "settings.alertTypes": "警报类型",
    "settings.weatherAlerts": "天气警报",
    "settings.weatherAlertsDesc": "洪水、干旱和暴风雨警告",
    "settings.marketUpdates": "市场价格更新",
    "settings.marketUpdatesDesc": "跟踪作物的价格变化",
    "settings.cropAdvisory": "作物咨询",
    "settings.cropAdvisoryDesc": "种植和收获建议",
    "settings.seedScanResults": "种子扫描结果",
    "settings.seedScanResultsDesc": "扫描完成和异常警报",
    "settings.delivery": "通知方式",
    "settings.emailDigest": "电子邮件摘要",
    "settings.emailDigestDesc": "每日邮件摘要",
    "settings.smsAlerts": "短信警报",
    "settings.smsAlertsDesc": "紧急警报通过短信发送",
    "settings.soundEffects": "声音效果",
    "settings.soundEffectsDesc": "应用内通知播放声音",
    "settings.quietHours": "静音时段",
    "settings.start": "开始",
    "settings.end": "结束",
    "settings.theme": "主题",
    "settings.light": "浅色",
    "settings.dark": "深色",
    "settings.fontSizeLabel": "字体大小",
    "settings.small": "小",
    "settings.medium": "中",
    "settings.large": "大",
    "settings.compactMode": "紧凑模式",
    "settings.compactModeDesc": "减少间距以获得更紧凑的布局",
    "settings.animations": "动画",
    "settings.animationsDesc": "启用动效和过渡",
    "settings.language": "语言",
    "settings.tempUnit": "温度单位",
    "settings.dateFormat": "日期格式",
    "settings.timezone": "时区",
    "settings.currency": "货币",
    "settings.shareLocation": "共享位置数据",
    "settings.shareLocationDesc": "允许天气和咨询功能使用您的农场位置",
    "settings.analyticsOptIn": "选择加入分析",
    "settings.analyticsOptInDesc": "通过共享匿名使用数据帮助改进平台",
    "settings.publicProfile": "公开个人资料",
    "settings.publicProfileDesc": "允许您所在地区的其他农民查看您的个人资料",
    "settings.twoFactor": "双重认证",
    "settings.twoFactorDesc": "为您的账户添加额外的安全层",
    "settings.dataExport": "数据导出",
    "settings.dataExportDesc": "允许下载您的农场数据和报告",
    "settings.accountActions": "账户操作",
    "settings.exportData": "导出我的数据",
    "settings.deleteAccount": "删除账户",
    "settings.saved": "设置已保存",
    "settings.savedDesc": "您的偏好已成功更新。",
    "nav.simulator": "风险模拟器",
    "simulator.title": "农场风险模拟器",
    "simulator.subtitle": "模拟天气、市场和种子质量对您作物计划的影响",
    "simulator.selectCrops": "选择您的作物计划",
    "simulator.scenarios": "情景参数",
    "simulator.weatherChange": "天气情景",
    "simulator.weatherNormal": "正常季节",
    "simulator.weatherMoreRain": "降雨增多",
    "simulator.weatherDrought": "干旱",
    "simulator.weatherMonsoon": "季风转变",
    "simulator.weatherFlood": "洪水风险",
    "simulator.weatherHeatwave": "热浪",
    "simulator.weatherLaNina": "拉尼娜",
    "simulator.weatherElNino": "厄尔尼诺",
    "simulator.cropPreset": "选择作物",
    "simulator.cropCustom": "手动输入",
    "simulator.cropPhoto": "照片识别",
    "simulator.cropPhotoDesc": "拍照或上传照片 — AI将为您识别作物。",
    "simulator.addCustomCrop": "添加",
    "simulator.identifyingCrop": "AI正在识别您的作物...",
    "simulator.marketFluctuation": "市场波动",
    "simulator.seedQuality": "种子质量",
    "simulator.germination": "发芽率",
    "simulator.runSimulation": "运行模拟",
    "simulator.reset": "重置",
    "simulator.totalRevenue": "预计总收入",
    "simulator.estimatedSeason": "本季预估",
    "simulator.avgFailureRisk": "平均失败风险",
    "simulator.lowRisk": "低风险 — 条件有利",
    "simulator.moderateRisk": "中等风险 — 谨慎行事",
    "simulator.highRisk": "高风险 — 考虑替代方案",
    "simulator.cropsPlanned": "计划作物",
    "simulator.diversification": "作物多样化",
    "simulator.cropBreakdown": "各作物分析",
    "simulator.simulatedOutcome": "模拟结果",
    "simulator.profitable": "盈利",
    "simulator.moderateRiskLabel": "中等风险",
    "simulator.highRiskLabel": "高风险",
    "simulator.estYield": "预计产量",
    "simulator.estRevenue": "预计收入",
    "simulator.failureRisk": "失败风险",
    "footer.farmer": "农民",
    "days": "天",
    "active": "活跃",
  },
  ta: {
    "nav.advisory": "ஆலோசனை",
    "nav.overview": "மேலோட்டம்",
    "nav.weather": "வானிலை முன்னறிவிப்பு",
    "nav.market": "சந்தை விலைகள்",
    "nav.crops": "பயிர் ஆலோசனை",
    "nav.seedIntegrity": "விதை நேர்மை",
    "nav.scanner": "விதை ஸ்கேனர்",
    "nav.evidence": "சான்று லாக்கர்",
    "nav.planner": "மீட்பு திட்டமிடல்",
    "nav.system": "அமைப்பு",
    "nav.alerts": "எச்சரிக்கைகள்",
    "nav.settings": "அமைப்புகள்",
    "nav.collapse": "சுருக்கு",
    "header.search": "எதையும் தேடுங்கள்...",
    "header.allSystems": "அனைத்து அமைப்புகளும் இயங்குகின்றன",
    "overview.status": "அமைப்பு நிலை:",
    "overview.operational": "இயங்குகிறது",
    "overview.risks": "கெடா மாவட்டத்தில் 2 அபாயங்கள் கண்டறியப்பட்டன",
    "overview.activeCrops": "செயலில் உள்ள பயிர்கள்",
    "overview.pendingScans": "நிலுவையில் உள்ள ஸ்கேன்கள்",
    "overview.alerts": "எச்சரிக்கைகள்",
    "overview.reports": "அறிக்கைகள்",
    "overview.recentActivity": "சமீபத்திய செயல்பாடு",
    "settings.title": "அமைப்புகள்",
    "settings.subtitle": "உங்கள் கணக்கு விருப்பங்கள் மற்றும் பண்ணை கட்டமைப்பை நிர்வகிக்கவும்",
    "settings.profile": "சுயவிவரம்",
    "settings.farm": "பண்ணை அமைப்புகள்",
    "settings.notifications": "அறிவிப்புகள்",
    "settings.display": "காட்சி",
    "settings.regional": "பிராந்திய",
    "settings.privacy": "தனியுரிமை & பாதுகாப்பு",
    "settings.save": "மாற்றங்களைச் சேமி",
    "settings.theme": "கருப்பொருள்",
    "settings.light": "ஒளி",
    "settings.dark": "இருள்",
    "settings.fontSizeLabel": "எழுத்துரு அளவு",
    "settings.small": "சிறிய",
    "settings.medium": "நடுத்தர",
    "settings.large": "பெரிய",
    "settings.language": "மொழி",
    "settings.saved": "அமைப்புகள் சேமிக்கப்பட்டன",
    "settings.savedDesc": "உங்கள் விருப்பங்கள் வெற்றிகரமாக புதுப்பிக்கப்பட்டன.",
    "footer.farmer": "விவசாயி",
    "days": "நாட்கள்",
    "active": "செயலில்",
  },
};
